services:
  website:
    image: noname602/bilibili_reranger_frontend
    ports:
      - '3000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - browser
      - backend
    networks:
      - bilibili-reranger

  browser:
    image: noname602/bilibili_reranger_browser
    networks:
      bilibili-reranger:
        aliases:
          - browser

  backend:
    image: noname602/bilibili_reranger_backend
    volumes:
      - ./config:/bilibili-backend/config
#      - ./plugin:/bilibili-backend/plugin
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_USER: ${POSTGRES_USER:-noname}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-nopassword}
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_HOST: ${POSTGRES_HOST:-postgres}
      DB_DELETE: ${POSTGRES_DELETE:-false}
    networks:
      bilibili-reranger:
        aliases:
          - backend

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-noname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nopassword}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - .env
    networks:
      bilibili-reranger:
        aliases:
          - ${POSTGRES_HOST:-postgres}

networks:
  bilibili-reranger:
    driver: bridge