worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        off;
    keepalive_timeout  60;

    # 主服务器配置
    server {
        listen 80;

        # 按照您的要求：捕获 /backend 及其后面的部分，清空之前的部分
        # 重写为只保留 /backend/?category=math 部分发往backend
        location ~* ^.*\/backend\/ {
            # 只将 /backend 及其后部分发送到内网
            rewrite ^.*\/backend\/(.*)$ /$1 break;
            proxy_pass http://backend ;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header 'Access-Control-Allow-Origin' '*'; # 生产环境请替换为前端的域名，例如 'http://your-frontend-domain.com'
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
        }

        location /api {
            proxy_pass http://api;
            proxy_set_header Host $host;
            # 传递原始请求头
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 如果请求中不包含 /backend，转发到前端
        location / {
            root /website;
            try_files $uri $uri/ /index.html;
        }
    }

    upstream backend {
        server backend:23223;
    }

    upstream api {
        server api:3000;
    }
}