services:
  frontend:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    domainname: frontend
    volumes:
      - ./session/codex:/home/vscode/.codex # You can change to C:\Users\username\.codex
      - ./session/codex:/root/.codex # You can change to C:\Users\username\.codex
      - ./session/gemini:/home/vscode/.gemini # You can change to C:\Users\username\.gemini
      - ./session/gemini:/root/.gemini # You can change to C:\Users\username\.gemini
      - ./session/codebuddy:/root/.codebuddy
      - ./session/codebuddy:/home/vscode/.codebuddy
      - ./session/claude:/root/.claude
      - ./session/claude:/home/vscode/.claude
    env_file:
      - .env
    depends_on:
      - backend
      - browser

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/passplease-organization/bilibili_reranger:frontend_dev}
    domainname: backend
    volumes:
      - ./backend_config:/bilibili-backend/config
    environment:
      DB_NAME: ${POSTGRES_DB:-postgres}
      DB_USER: ${POSTGRES_USER:-noname}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-nopassword}
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_HOST: ${POSTGRES_HOST:-postgres}
      DB_DELETE: ${POSTGRES_DELETE:-false}
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    domainname: ${POSTGRES_HOST:-postgres}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-noname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nopassword}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - ./postgres-data:/var/lib/postgresql

  browser:
    image: ${BROWSER_IMAGE:-ghcr.io/passplease-organization/bilibili_reranger:browser_for_dev}
    domainname: browser
    env_file:
      - .env
    environment:
      BROWSER_DEBUG_ENABLED: 1

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
      - browser