services:
  frontend:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    domainname: frontend
    env_file:
      - env.list
    depends_on:
      - backend

  backend:
    image: ghcr.io/passplease/bilibili_reranger:frontend_dev
    domainname: backend
    env_file:
      - env.list
    volumes:
      - ./backend_config:/bilibili-backend/config

  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf