name: Dev Container
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - express/Dockerfile

jobs:
  call-workflow-passing-data:
    uses: passplease/Bilibili-Reranger/.github/workflows/docker.yml@master
    with:
      ref: "frontend"