name: Dev Container
on:
  workflow_dispatch:
  fork:
  push:
    paths:
      - Dockerfile
      - express/Dockerfile
      - .github/workflows/docker.yml

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      packages: write
    uses: passplease-organization/Bilibili-Reranger/.github/workflows/docker.yml@master
    with:
      ref: "frontend"