name: Release Backend
on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  Create-Image:
    runs-on: ubuntu-22.04
    environment: Publish
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: noname602
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/bilibili_reranger:${{ github.event.release.tag_name }}
            docker.io/noname602/bilibili_reranger:${{ github.event.release.tag_name }}
            docker.io/noname602/bilibili_reranger:latest